apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-976401375f1e44959fc4400205dd10a5-depl
  labels:
    app: coll-976401375f1e44959fc4400205dd10a5
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-976401375f1e44959fc4400205dd10a5
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-976401375f1e44959fc4400205dd10a5
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-976401375f1e44959fc4400205dd10a5
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-976401375f1e44959fc4400205dd10a5
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping